name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.13
          bundle install
      - name: Generate RSpec binstub
        run: |
          bundle exec rails generate rspec:install
          bundle binstub rspec-core
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rspec
      - name: Ensure minimum test coverage
        run: |
          coverage=$(grep -Po '(?<=lines\.\scoverage:\s)\d+\.\d+' coverage/.last_run.json)
          if (( $(echo "$coverage < 95" | bc -l) )); then
            echo "Test coverage ($coverage%) is below the minimum required (95%)."
            exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.13
          bundle install
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel