name: "Ruby on Rails CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Precompile assets (if necessary)
        run: bin/rails assets:precompile RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec

      - name: Ensure minimum test coverage
        run: |
          coverage=$(grep -Po '(?<=lines\.\scoverage:\s)\d+\.\d+' coverage/.last_run.json)
          if (( $(echo "$coverage < 95" | bc -l) )); then
            echo "Test coverage ($coverage%) is below the minimum required (95%)."
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Security audit dependencies
        run: bin/bundler-audit --update

      - name: Security audit application code
        run: bin/brakeman -q -w2

      - name: Lint Ruby files
        run: bin/rubocop --parallel
